[project]
name = "prisoners-dilemma"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pytest>=8.3.4",
    "stqdm>=0.0.5",
    "streamlit>=1.41.1",
    "watchdog>=6.0.0",
]
